version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/opu/docker/npm/data:/data
      - /home/opu/docker/npm/letsencrypt:/etc/letsencrypt
networks:
  default:
    external: true
    name: caddy