version: '3.3'
services:
    server:
        container_name: vaultwarden
        volumes:
            - '/home/opu/docker/vaultwarden/data:/data/'
        environment:
            - SIGNUPS_ALLOWED=true
            - ADMIN_TOKEN=randomPassword40characters
        ports:
            - '8888:80'
        image: 'vaultwarden/server:latest'
        restart: unless-stopped
        
networks:
    default:
        external: true
        name: caddy