services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    volumes:
      - /home/opu/docker/emby/config:/config
      - /media/server/jellyfin/tvshows:/data/tvshows
      - /media/server/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
networks:
  default:
    external: true
    name: caddy