version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Asia/Dhaka'
      WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - '/home/opu/docker/pihole/etc-pihole:/etc/pihole'
      - '/home/opu/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
networks:
  default:
    external: true
    name: caddy