version: '3.9'
services:
    adguardhome:
        image: 'adguard/adguardhome:latest'
        ports:
            - '3000:3000/tcp'
            - '443:443/udp'
            - '443:443/tcp'
            - '80:80/tcp'
            - '53:53/udp'
            - '53:53/tcp'
        volumes:
            - '/home/opu/docker/adguard/conf:/opt/adguardhome/conf'
            - '/home/opu/docker/adguard/work:/opt/adguardhome/work'
        restart: unless-stopped
        container_name: adguardhome
