version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_BASEURL: ""
    volumes:
      - "/home/opu/docker/navidrome/data:/data"
      - "/media/server/navidrome/music:/music:ro"
    restart: unless-stopped
networks:
  default:
    external: true
    name: caddy