version: '3.9'
services:
    watchtower:
        image: containrrr/watchtower:latest
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        container_name: watchtower
        restart: unless-stopped

networks:
    default:
        external: true
        name: caddy
