version: '3.9'
services:
    cloudflared:
        command: 'tunnel --no-autoupdate run --token eyJhIjoiNDJkYjhlYjliNWE0YmZmOGIwOTQ5OTA4MjYyMmQzNWIiLCJ0IjoiOTIxYjg3ZGMtNDk1Yy00NzE0LWFhMzktZDVkMjVkMjQ3OWQ0IiwicyI6Ik9EQTFOVEV4WmpjdFlUVTNNQzAwWVdaakxXSTBNV1F0TVRRM016RmtZMlV6TmpJdyJ9'
        image: 'cloudflare/cloudflared:latest'
        restart: unless-stopped
networks:
  default:
    external: true
    name: caddy