version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Dhaka
       ports:
            - 5055:5055
       volumes:
            - /home/opu/docker/jellyseerr/config:/app/config
       restart: unless-stopped
networks:
   default:
      external: true
      name: caddy